@extends('admin.layouts.app')
@section('title', 'Edit Lokasi')
@section('content')
<div class="mb-6"><h1 class="text-3xl font-bold text-gray-900">Edit Lokasi</h1></div>
<form action="{{ route('admin.peta.update', $peta->id) }}" method="POST" enctype="multipart/form-data" x-data="{ preview: '{{ $peta->gambar ? asset('storage/' . $peta->gambar) : '' }}' }">
@csrf @method('PUT')
<div class="grid grid-cols-1 lg:grid-cols-3 gap-6">
<div class="lg:col-span-2 bg-white rounded-xl shadow-sm border border-gray-100 p-6 space-y-4">
<div><label class="block text-sm font-medium text-gray-700 mb-2">Nama Lokasi *</label><input type="text" name="nama_lokasi" required value="{{ old('nama_lokasi', $peta->nama_lokasi) }}" class="w-full px-4 py-3 rounded-lg border border-gray-300 focus:ring-2 focus:ring-green-500"></div>
<div><label class="block text-sm font-medium text-gray-700 mb-2">Deskripsi</label><textarea name="deskripsi" rows="4" class="w-full px-4 py-3 rounded-lg border border-gray-300 focus:ring-2 focus:ring-green-500">{{ old('deskripsi', $peta->deskripsi) }}</textarea></div>
<div class="grid grid-cols-2 gap-4"><div><label class="block text-sm font-medium text-gray-700 mb-2">Latitude *</label><input type="number" step="any" name="latitude" required value="{{ old('latitude', $peta->latitude) }}" placeholder="-6.2088" class="w-full px-4 py-3 rounded-lg border border-gray-300 focus:ring-2 focus:ring-green-500"></div><div><label class="block text-sm font-medium text-gray-700 mb-2">Longitude *</label><input type="number" step="any" name="longitude" required value="{{ old('longitude', $peta->longitude) }}" placeholder="106.8456" class="w-full px-4 py-3 rounded-lg border border-gray-300 focus:ring-2 focus:ring-green-500"></div></div>
<div><label class="block text-sm font-medium text-gray-700 mb-2">Gambar (Opsional)</label><label class="flex flex-col items-center px-4 py-6 bg-white text-gray-500 rounded-lg border-2 border-gray-300 border-dashed cursor-pointer hover:bg-gray-50"><svg class="w-12 h-12 mb-3" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M7 16a4 4 0 01-.88-7.903A5 5 0 1115.9 6L16 6a5 5 0 011 9.9M15 13l-3-3m0 0l-3 3m3-3v12"/></svg><span class="text-sm font-medium">Upload gambar</span><input type="file" name="gambar" accept="image/*" class="hidden" @change="preview = URL.createObjectURL($event.target.files[0])"></label><div x-show="preview" class="mt-4"><img :src="preview" class="max-h-64 rounded-lg shadow-lg"></div></div>
</div>
<div class="space-y-6">
<div class="bg-white rounded-xl shadow-sm border border-gray-100 p-6"><h3 class="text-lg font-bold text-gray-900 mb-4">Info</h3><div class="mb-4"><label class="block text-sm font-medium text-gray-700 mb-2">Kategori *</label><select name="kategori" required class="w-full px-4 py-3 rounded-lg border border-gray-300 focus:ring-2 focus:ring-green-500"><option value="fasilitas_umum" {{ old('kategori', $peta->kategori) === 'fasilitas_umum' ? 'selected' : '' }}>Fasilitas Umum</option><option value="wisata" {{ old('kategori', $peta->kategori) === 'wisata' ? 'selected' : '' }}>Wisata</option><option value="pemerintahan" {{ old('kategori', $peta->kategori) === 'pemerintahan' ? 'selected' : '' }}>Pemerintahan</option><option value="lainnya" {{ old('kategori', $peta->kategori) === 'lainnya' ? 'selected' : '' }}>Lainnya</option></select></div><div class="flex items-center"><input type="checkbox" name="tampilkan" value="1" {{ old('tampilkan', $peta->tampilkan) ? 'checked' : '' }} class="w-4 h-4 text-green-600"><label class="ml-2 text-sm font-medium text-gray-700">Tampilkan di peta</label></div></div>
<div class="bg-white rounded-xl shadow-sm border border-gray-100 p-6"><button type="submit" class="w-full bg-green-600 text-white px-6 py-3 rounded-lg hover:bg-green-700 font-medium mb-3">Simpan</button><a href="{{ route('admin.peta.index') }}" class="block w-full text-center bg-gray-100 text-gray-700 px-6 py-3 rounded-lg hover:bg-gray-200 font-medium">Batal</a></div>
</div>
</div>
</form>
@endsection
